### ISSUE TITLE
As a new user, I should be able to create a new to-do list with items

### ISSUE THREAD

**Issue by matt-ros** [matt-ros/moving-day-client#2]
- [ ] Create POST /lists endpoint
- [ ] Create POST /lists/:list_id/items endpoint
- [ ] Create table for lists
- [ ] Create table for list items
